<a href="https://colab.research.google.com/github/ZenoZoldyck/hand_on_tensorflow/blob/main/00tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)


2.4.1


In [2]:
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 120], [11, 13]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10, 120],
       [ 11,  13]], dtype=int32)>

In [7]:
an = tf.constant([[12, 13],
                  [5, 6],
                  [45, 63]], dtype = tf.float16)

an

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[12., 13.],
       [ 5.,  6.],
       [45., 63.]], dtype=float16)>

In [8]:
an.ndim

2

In [9]:
tensor = tf.constant([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                      [7, 8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [10]:
tensor.ndim

3

In [11]:
abc = tf.Variable([10, 7])
abc

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [12]:
abc[0].assign(5)
abc

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [13]:
a = tf.random.Generator.from_seed(45).normal(shape = (3, 2))
b = tf.random.Generator.from_seed(67).uniform(shape = (3, 2, 2))
b

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0.43336582, 0.51829636],
        [0.8555572 , 0.21962428]],

       [[0.76091194, 0.04762888],
        [0.5131633 , 0.97339594]],

       [[0.33341944, 0.03152311],
        [0.28874612, 0.58736026]]], dtype=float32)>

In [14]:
import tensorflow as tf

gy = tf.Variable([10, 10])
gy

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [15]:
gy[0].assign(8)
gy

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>

In [16]:
shuffled = tf.constant([[5, 5],
                        [8, 3],
                        [7,1],
                        [2, 2],
                        [9, 5]])
tf.random.set_seed(45)  # global level seed
tf.random.shuffle(shuffled, seed = 47)  # operation level seed


<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[7, 1],
       [8, 3],
       [5, 5],
       [9, 5],
       [2, 2]], dtype=int32)>

In [17]:
tf.ones([3, 2, 3], tf.float32)

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [18]:
import numpy as np
A = np.arange(1, 10, dtype = np.int32)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [19]:
tf.constant(A, shape = (3, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [20]:
aaa = tf.zeros([2, 3, 3, 4], tf.int32)
aaa

<tf.Tensor: shape=(2, 3, 3, 4), dtype=int32, numpy=
array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]], dtype=int32)>

In [21]:
aaa.shape[1]

3

In [22]:
aaa[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [23]:
aaa[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=int32, numpy=array([[[[0, 0, 0, 0]]]], dtype=int32)>

In [24]:
aaa[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 3, 1), dtype=int32, numpy=
array([[[[0],
         [0],
         [0]]]], dtype=int32)>

In [25]:
two = tf.constant([[2, 3],
                   [6, 8]])
three = two[..., tf.newaxis]
three

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[6],
        [8]]], dtype=int32)>

In [26]:
tf.expand_dims(two, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[6],
        [8]]], dtype=int32)>

In [27]:
tensor = tf.constant([[10, 5], [2, 6]])
tensor - 8

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, -3],
       [-6, -2]], dtype=int32)>

In [28]:
tf.multiply(tensor, 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 45],
       [18, 54]], dtype=int32)>

In [29]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110,  80],
       [ 32,  46]], dtype=int32)>

In [30]:
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[11, 12], [4, 3]])
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[19, 18],
       [49, 48],
       [79, 78]], dtype=int32)>

In [31]:
s = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
s


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [32]:
tf.transpose(s)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]], dtype=int32)>

In [33]:
y = tf.constant([1.4, 2.5])
y.dtype
tf.cast(y, dtype = tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.4, 2.5], dtype=float16)>

In [34]:
D = tf.constant([-58, -44])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([58, 44], dtype=int32)>

In [35]:
A = tf.constant([[4, -5],
                 [-11, 75]])
tf.abs(A)
print(tf.reduce_max(A))
print(tf.reduce_min(A))
print(tf.reduce_sum(A))
print(tf.reduce_mean(A))

tf.Tensor(75, shape=(), dtype=int32)
tf.Tensor(-11, shape=(), dtype=int32)
tf.Tensor(63, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


In [36]:
S = tf.random.Generator.from_seed(452)
S.normal(shape = (2, 3, 5))

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[ 0.58248633, -1.3227581 ,  1.2173856 ,  0.75051606,
         -1.1586719 ],
        [ 0.15267496, -3.0746865 , -1.6406803 ,  0.13963513,
         -0.7290472 ],
        [-1.3584449 ,  0.6042902 ,  1.8241866 ,  0.16743198,
          0.11442922]],

       [[ 0.2823798 ,  0.0631539 , -0.68608636, -0.11220581,
          2.451337  ],
        [-1.2933265 ,  1.8967754 , -0.5769588 ,  0.3737864 ,
          0.63057506],
        [ 0.8946543 ,  0.16760615,  1.0525804 , -0.18441029,
         -0.16581555]]], dtype=float32)>

In [37]:
import tensorflow_probability as tfp
tfp.stats.variance(A)
tf.math.reduce_std(tf.cast(A, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=34.622066>

In [38]:
tf.argmax(tf.reshape(A, shape = (4,)))
tf.reshape(A, shape = (4,))[tf.argmax(tf.reshape(A, shape = (4,)))] 

<tf.Tensor: shape=(), dtype=int32, numpy=75>

In [39]:
D = tf.constant(tf.random.uniform(shape = [50]), shape = [1, 1, 1, 50])
tf.squeeze(D), tf.squeeze(D).shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.48913598, 0.30816448, 0.8261548 , 0.25587916, 0.2993518 ,
        0.2643453 , 0.21094537, 0.22731137, 0.01557994, 0.12873471,
        0.3316598 , 0.42108238, 0.8701608 , 0.65981686, 0.5743673 ,
        0.6854216 , 0.6515837 , 0.19545841, 0.1441735 , 0.9233247 ,
        0.42670476, 0.8457639 , 0.3934058 , 0.9006833 , 0.47969007,
        0.6867969 , 0.67909396, 0.7238083 , 0.7927431 , 0.47818553,
        0.47793758, 0.28856158, 0.69985783, 0.5915674 , 0.01672316,
        0.49891758, 0.38331974, 0.6024455 , 0.60487247, 0.51338553,
        0.21195805, 0.507064  , 0.27594423, 0.34573162, 0.01471639,
        0.47635663, 0.8088087 , 0.08854103, 0.77666366, 0.00165653],
       dtype=float32)>, TensorShape([50]))

In [40]:
A = tf.constant([0, 1, 2, 3])
tf.one_hot(A, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [41]:
H = tf.range(1, 10)
tf.square(H)
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [42]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [43]:
G = tf.constant(np.array([1, 2, 3, 4]))
G
type(np.array(G))

numpy.ndarray

In [47]:
W = tf.constant([[1, 5], [6, 6]])
tf.shape(W)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [51]:
W.ndim, tf.size(W)
W

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [6, 6]], dtype=int32)>

In [52]:
tf.reshape(W, shape = (4, 1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [5],
       [6],
       [6]], dtype=int32)>